### ISSUE TITLE
"No named parameter with the name 'shadowThemeOnly'" in newest Flutter Beta release

### ISSUE THREAD

**Issue by TomStoffen** [jamesblasco/modal_bottom_sheet#116] opened 2020-11-20 08:51 UTC
Updated Flutter Beta to 1.24.0-10.2.pre this morning and this error appeared:

```../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-1.0.1-dev/lib/src/bottom_sheets/cupertino_bottom_sheet.dart:344:46: Error: No named parameter with the name 'shadowThemeOnly'.
    final isCupertinoApp = Theme.of(context, shadowThemeOnly: true) == null;
                                             ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-1.0.1-dev/lib/src/bottom_sheets/material_bottom_sheet.dart:42:32: Error: No named parameter with the name 'shadowThemeOnly'.
      theme: Theme.of(context, shadowThemeOnly: true),
                               ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
```

Removing `shadowThemeOnly: true` from these two files solves it, and the plugin seems to run fine in my app.

**Comment by jamesblasco** [comment] 2020-11-20 09:12
Please, try to look for similar issues before publishing one. There are already 4 closed issues related to this change 😅.

Duplicate of https://github.com/jamesblasco/modal_bottom_sheet/issues/109
This is fixed in the last version 1.0.0

**Closed by jamesblasco** 2020-11-20 09:12 UTC
