### ISSUE TITLE
showCupertinoModalBottomSheet build method called multiple times

### ISSUE THREAD

**Issue by robvr** [jamesblasco/modal_bottom_sheet#90] opened 2020-10-11 16:43 UTC
Whenever I call showCupertinoModalBottomSheet the build method of the widget passed to the build method is called multiple times. Any ideas on how to tackle this situation? Thx

**Comment by jamesblasco** [comment] 2020-10-11 17:31
Duplicate of https://github.com/jamesblasco/modal_bottom_sheet/issues/56

**Closed by jamesblasco** 2020-10-11 17:31 UTC
