### ISSUE TITLE
Cannot build with Flutter beta

### ISSUE THREAD

**Issue by orestesgaolin** [jamesblasco/modal_bottom_sheet#87] opened 2020-09-28 22:00 UTC
When building the app with Flutter beta following error appears:

```
    5 warnings generated.
    ../../../.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.2/lib/src/bottom_sheet.dart:303:43: Error: Too few positional arguments: 1 required, 0 given.
            _velocityTracker = VelocityTracker();
                                              ^
    ../../../fvm/versions/beta/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't match.
      VelocityTracker(this.kind);
      ^^^^^^^^^^^^^^^

```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G73, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (4 available)
```

**Comment by jamesblasco** [comment] 2020-09-28 22:19
This change has been reversed in master.

Please use the version **0.2.1+2-dev** in the meantime 

Duplicate of : https://github.com/jamesblasco/modal_bottom_sheet/issues/69

**Comment by orestesgaolin** [comment] 2020-09-28 22:20
Thanks for clarification!

**Closed by jamesblasco** 2020-09-28 22:19 UTC

**Comment by orestesgaolin** [comment] 2020-09-29 08:50
Wanted to let you know that today's beta version warns about deprecation of VelocityTracker

**Comment by jamesblasco** [comment] 2020-09-29 10:03
Yess I know, thanks. Once 1.22.0 is released in master I will make the new change to the new VelocityTracker constructor. 

With one breaking change, it has been enough chaos hehe 😆
