### ISSUE TITLE
Doesn't go back to the top sometimes

### ISSUE THREAD

**Issue by HiroshiHorie** [jamesblasco/modal_bottom_sheet#13] opened 2020-04-30 19:46 UTC
Almost perfect except :

1. sometimes when I let ago while dragging,
the sheet doesn't go back to the top and just stops there. It happens quite frequently.

2. The animation curve is ugly.
Please provide a parameter to pass the animation curve. Haven't read the code but is this related to PageRoute ?

3. Provide a parameter for the dismiss threshold.
Personally, I feel it's a bit hard to dismiss. I prefer it easier to dismiss.

I am using dev channel of flutter.

Gif:
![issue01](https://user-images.githubusercontent.com/548776/80752524-33c5a900-8b5e-11ea-9e5b-fe752d4c7a86.gif)

Regards
Hiroshi

**Comment by jamesblasco** [comment] 2020-04-30 20:13
Thanks submitting the issue.

I will take a look to the issue about the sheet not going back to the top. Is the bottom sheet param expanded: true? Are you using your custom Bottom Sheet, could you share me the code of the container so I can try with that one?

About the second and third point I agree should be improved and allow to customization. I am lacking of free time this month to spend in building more features for this. But I will try to work on it after that

**Comment by HiroshiHorie** [comment] 2020-05-01 04:44
Hi, this is the code I used:
```
          showFloatingModalBottomSheet(
            context: context,
            builder: (context, scrollController) => Container(
              height: 500,
              child: ListView.builder(
                shrinkWrap: true,
                controller: scrollController,
                itemBuilder: (context, i) => ListTile(
                  title: Text('Test'),
                ),
              ),
            ),
          );
```

**showFloatingModalBottomSheet** is from your sample code.

Thank you for the effort, if I also have time I will try to contribute.

**Comment by bierbaumtim** [comment] 2020-05-01 17:28
I have started to expose the Curve for the animation and will open a PR later this day.

**Comment by jamesblasco** [comment] 2020-05-05 07:51
I am not able to replicate the issue @HiroshiHorie, I will keep looking. Check if without 
`shrinkWrap: true,` the issue doesn't appear.

I am going to make the threshold lower until I found a better solution. I will probably work on that together with support multiple heights. 

@bierbaumtim did an awesome job and exposed the Curve and now you can change it through `animationCurve` from `ModalBottomSheetRoute`. I will publish the new version of the package to pub at the end of the week

**Comment by HiroshiHorie** [comment] 2020-05-05 12:17
@jamesblasco & @bierbaumtim Thank you! I'm looking forward to the new version 😊
When I have time, I will try to figure out in what conditions the bug occurs.

**Comment by jamesblasco** [comment] 2020-05-05 12:24
Also I discover I had a bug with closing the modal with a scroll view with ClampingScrollPhysics(default for Android).
You are supposed to be able to close the modal by dragging down fast even if you not reach the threshold. Once that is fixed, the UX will improve.

**Comment by HiroshiHorie** [comment] 2020-05-07 09:42
Hello, I tried merged commit on master but I don't know why the animation doesn't seem to be using the animationCurve. I am specifying it on the parameter.

```
Future<T> showFloatingModalBottomSheet<T>({
  @required BuildContext context,
  @required ScrollWidgetBuilder builder,
  Color backgroundColor,
}) async {
  //
  //
  final result = await showCustomModalBottomSheet(
    context: context,
    builder: builder,
    containerWidget: (_, animation, child) => FloatingModal(
      child: child,
    ),
    expand: false,
    animationCurve: Curves.easeOutCirc,
  );

  return result;
}
```

**Comment by jamesblasco** [comment] 2020-05-07 10:42
Mmm I see where the problem is, sorry I forgot about this.
The curved is disabled [here](https://github.com/jamesblasco/modal_bottom_sheet/blob/7a0e9b7ae2b514c22d9573f3ea3d1e7233e4c1d8/lib/src/bottom_sheet.dart#L299) until I solve another problem related.

Dragging the modal modifies the value of the animation controller lineally, if we add a curve to the animation the dragging offset will be different of the offset of the modal.

I will enable it, but the dragging experience could look weird until I fix that

**Comment by HiroshiHorie** [comment] 2020-05-08 10:59
That seems like a complicated problem since if we are going to use an animation curve (which is not linear), we can't simply reverse the animation. I suppose the dragging needs to be a separate logic from the animation.

**Comment by jamesblasco** [comment] 2020-05-08 11:22
Yeah the final idea is that dragging and animation work in sync but not in the same animation controller. I was planning to work on this for implementing multi-height support but I am lacking of time for work on this until the summer

**Comment by sezny** [comment] 2020-05-28 11:04
> Also I discover I had a bug with closing the modal with a scroll view with ClampingScrollPhysics(default for Android).
> You are supposed to be able to close the modal by dragging down fast even if you not reach the threshold. Once that is fixed, the UX will improve.

Hello @jamesblasco  :) Any update on this ? It would be a great improvement !

**Comment by jamesblasco** [comment] 2020-05-28 11:53
I am a bit bussy these days and can't test it properly. I think I have a fix and I uploaded to the branch [small_bug_fixes](https://github.com/jamesblasco/modal_bottom_sheet/tree/small_bug_fixes)

You can try it there, let me know if it works for you:
```yaml
modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet/
      ref: small_bug_fixes
```

I will come back to this during this summer

**Comment by sezny** [comment] 2020-05-28 13:00
> I am a bit bussy these days and can't test it properly. I think I have a fix and I uploaded to the branch [small_bug_fixes](https://github.com/jamesblasco/modal_bottom_sheet/tree/small_bug_fixes)
> 
> You can try it there, let me know if it works for you:
> 
> ```yaml
> modal_bottom_sheet:
>     git:
>       url: https://github.com/jamesblasco/modal_bottom_sheet/
>       ref: small_bug_fixes
> ```
> 
> I will come back to this during this summer

It works ! Thanks a lot !

**Comment by YeungKC** [comment] 2020-06-13 14:58
@jamesblasco 
why remove duration param?

I think the animation should add inCurve and outCurve

**Comment by jamesblasco** [comment] 2020-07-05 12:23
@HiroshiHorie are you still having the same issue? Otherwise, I will close this issue.

The issue for Animation Curve request will be #21

**Comment by HiroshiHorie** [comment] 2020-07-08 15:21
@jamesblasco Thanks for the time and effort, I have respect for all contributors to open source. I wish I had more time & skills to contribute.

**Closed** 2020-07-08 15:21 UTC
